# Multiple Linear Regression - 
- In wich we multiple Independent features and single Dependent feature.

In [4]:
import numpy as np
import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# EDA

In [6]:
startups_df = pd.read_csv(r'D:\AI & ML\Machine_Learning_19\Supervise_learning\Regression\50_Startups.csv')
startups_df.head(5)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
startups_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [ ]:
startups_df.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [ ]:
startups_df.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
Profit             float64
dtype: object

In [ ]:
startups_df.duplicated().sum()

0

In [ ]:
startups_df['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

# LabelEncoder - 
- Use to convert categorical values to numericals.

In [ ]:
from sklearn.preprocessing import LabelEncoder
lab_encoder = LabelEncoder()

startups_df['State'] = LabelEncoder().fit_transform(startups_df['State'])

In [7]:
startups_df.head(5)  # Alfabatical numbering kari hai. isliye New york ko 2 , Cali ko 0 or Flori ko 1

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

# Feature selection Feature

In [9]:
Independent_feat = startups_df.iloc[ : , :-1]  # Bss -1 profit ko chod kr baki sabhi column le lega.
Dependent_feat = startups_df.iloc[: ,-1]   # Dependent_feat me bss Profit wala column save huaa.

In [10]:
Independent_feat.head(10)

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida
5  131876.90        99814.71        362861.36    New York
6  134615.46       147198.87        127716.82  California
7  130298.13       145530.06        323876.68     Florida
8  120542.52       148718.95        311613.29    New York
9  123334.88       108679.17        304981.62  California

In [11]:
Dependent_feat.head(10)

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
5    156991.12
6    156122.51
7    155752.60
8    152211.77
9    149759.96
Name: Profit, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

X_train ,X_test ,Y_train,Y_test = train_test_split(Independent_feat,Dependent_feat,test_size=0.2)

In [ ]:
print(X_train.shape, X_test.shape)
print(Y_train.shape, Y_test.shape)

(40, 4) (10, 4)
(40,) (10,)

In [ ]:
from sklearn.linear_model import LinearRegression

train_model = LinearRegression().fit(X_train,Y_train)  # fit batata hai ki kin do data se mujhe sikhna hai.
train_model

LinearRegression()

In [ ]:
prediction = train_model.predict(X_test)
prediction

array([ 63858.07601016,  97611.24512016, 117560.09731522, 134669.02184709,
       109713.75040102, 113687.41504158,  90063.33323278, 100876.50984947,
        97570.53923018,  89229.79755087])

In [ ]:
Y_test

44     65200.33
32     97427.84
21    111313.02
10    146121.95
26    105733.54
19    122776.86
35     96479.51
29    101004.64
33     96778.92
34     96712.80
Name: Profit, dtype: float64

In [ ]:
Diff = pd.DataFrame({'Actual':Y_test,
                     'Predicted':prediction})

Diff

       Actual      Predicted
44   65200.33   63858.076010
32   97427.84   97611.245120
21  111313.02  117560.097315
10  146121.95  134669.021847
26  105733.54  109713.750401
19  122776.86  113687.415042
35   96479.51   90063.333233
29  101004.64  100876.509849
33   96778.92   97570.539230
34   96712.80   89229.797551

In [ ]:
from sklearn.metrics import r2_score

r2_score(Y_test,prediction)*100

90.56297948399529


---

### 🔹 Absolute Difference क्या होता है?
मान लो **Actual value (Y)** = 50 और **Predicted value (Ŷ)** = 45  
Error = \( Y - Ŷ = 50 - 45 = 5 \)  

अगर prediction बड़ा हो गया होता, जैसे 55, तो error = \( 50 - 55 = -5 \)  
लेकिन negative error को समझना मुश्किल होता है, इसलिए हम **absolute value** लेते हैं (मतलब sign हटाकर सिर्फ दूरी देखते हैं)।  
तो error = | -5 | = 5  

👉 Absolute difference = Actual और Predicted के बीच की दूरी, चाहे prediction ऊपर हो या नीचे।

---

### 🔹 Units का मतलब
Error हमेशा उसी unit में होगा जिस unit में तुम्हारा target variable है।  
- अगर तुम **house price (₹ में)** predict कर रहे हो → error भी ₹ में होगा।  
- अगर तुम **weight (kg में)** predict कर रहे हो → error भी kg में होगा।  

इसलिए RMSE और MAE को समझना आसान है क्योंकि वो उसी unit में रहते हैं।

---

### 🔹 Square क्यों करते हैं?
1. **Negative error हटाने के लिए**: अगर सिर्फ difference लेते हैं तो कुछ errors positive होंगे, कुछ negative, और average करने पर cancel हो सकते हैं। Square करने से सब positive हो जाते हैं।  
2. **बड़े errors को ज्यादा importance देने के लिए**:  
   - Example: Error = 10 → Square = 100  
   - Error = 2 → Square = 4  
   मतलब बड़े errors बहुत ज्यादा बढ़ जाते हैं, जिससे model को बड़े गलत predictions avoid करने की motivation मिलती है।
   - Example: Useful जब हम चाहते हैं कि बड़े errors को ज्यादा importance मिले। (MSE)

---

### 🔹 तीनों Metrics का Simple Example
मान लो Actual values = [10, 20, 30]  
Predicted values = [12, 18, 33]  

Errors = [2, -2, 3]  

- **MAE** = Average(|2|, |-2|, |3|) = (2+2+3)/3 = 2.33  
- **MSE** = Average(2², (-2)², 3²) = (4+4+9)/3 = 5.67  
- **RMSE** = √5.67 ≈ 2.38  

👉 देखो:  
- MAE और RMSE लगभग बराबर हैं (units में समझ आते हैं)।  
- MSE बड़ा है क्योंकि square करने से बड़े errors और बड़े हो गए।

---

### 🔹 Summary
- **MAE** → Average गलती, simple और समझने में आसान।  
- **MSE** → बड़े errors को ज्यादा penalize करता है।  
- **RMSE** → Error को उसी unit में बताता है, practical interpretation आसान।  

---

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print(f"Mean absolute error : {mean_absolute_error(Y_test,prediction)}")
print(f"Mean Squere error : {mean_squared_error(Y_test,prediction)}")
print(f"Root mean squere error : {np.sqrt(mean_squared_error(Y_test,prediction))}")

Mean absolute error : 4711.424853463898
Mean Squere error : 36829663.42609848
Root mean squere error : 6068.744798234515

## We give new data for predict.
- Important points.

1. Sequeance and Number of Element must be same.

In [ ]:
arr = np.array([[165349.20,	136897.80,	471784.10,	2]])
new_pre = train_model.predict(arr)

new_pre

array([192614.81992996])

#  --- Model Serialization and Deserialization (Using pickel)---
---

In [ ]:
import pickle

In [ ]:
with open('Pridiction.pkl','wb') as file:
    pickle.dump(train_model,file)

In [ ]:
with open('Pridiction.pkl','rb') as file:
    model = pickle.load(file)

 

---

### 🔹 Process का नाम
- **Serialization** → किसी Python object (जैसे ML model) को binary format में बदलकर file में save करना।  
  👉 यहाँ `pickle.dump()` यही काम कर रहा है।  
- **Deserialization** → उस binary file को वापस पढ़कर original Python object में बदलना।  
  👉 यहाँ `pickle.load()` यही काम कर रहा है।  

इसलिए इस पूरे process को **Model Persistence (Saving & Loading a trained model)** भी कहते हैं।  

---

### 🔹 क्यों ज़रूरी है?
- हर बार model को retrain करने की ज़रूरत नहीं।  
- Time और resources बचते हैं।  
- Trained model को दूसरों के साथ share कर सकते हो।  
- Production में deploy करने के लिए model को save करना ज़रूरी होता है।  

---

### 🔹 Simple Analogy
सोचो तुमने एक किताब पढ़कर notes बनाए।  
- **Serialization (dump)** = Notes को notebook में लिखकर सुरक्षित रखना।  
- **Deserialization (load)** = Notebook खोलकर notes फिर से पढ़ना।  

---

👉 तो तुम्हारे code में जो हुआ उसे हम कहते हैं:  
**Pickle का use करके ML model को serialize (save) और deserialize (load) करना।**

---

In [ ]:
array = np.array([[170349.20,	126897.80,	371784.10,	0]])
prediction = model.predict(array)
print(prediction)

[193445.38651936]


---

### 🔹 कैसे Share कर सकते हो?
1. **File भेजना**  
   - तुम `ProfitPrediction.pkl` file को अपने दोस्त को Email, WhatsApp, Google Drive, या Pen Drive से भेज सकते हो।  
   - यह file binary format में तुम्हारा trained model store करती है।  

2. **Friend कैसे Use करेगा?**  
   - सबसे पहले उसे वही libraries install करनी होंगी (जैसे `scikit-learn`, `numpy`, `pickle`)।  
   - फिर वो file को load करेगा इस तरह:
     ```python
     import pickle

     # Load model
     with open("ProfitPrediction.pkl","rb") as file:
         model = pickle.load(file)

     # Prediction
     X_test = [[6],[7]]
     Y_predict = model.predict(X_test)
     print("Predictions:", Y_predict)
     ```
   - अब उसे वही trained model मिल जाएगा जो तुमने बनाया था, और वो बिना retrain किए prediction कर सकता है।  

---

### 🔹 इस Process को क्या कहते हैं?
👉 इसे कहते हैं **Model Deployment / Model Sharing using Pickle**  
या फिर **Model Persistence** (trained model को future use और sharing के लिए सुरक्षित रखना)।  

---

💡 Practical फायदा:  
- तुम एक बार train करके model save कर दो।  
- दोस्त को सिर्फ `.pkl` file दो।  
- वो बिना retrain किए सीधे prediction कर सकता है।  

---